FROM openjdk:21-bookworm AS builder

WORKDIR /src

COPY src src
COPY .mvn .mvn
COPY mvnw .
COPY pom.xml .

# compile the Java application
RUN ./mvnw clean package -Dmaven.skip.test=true

FROM openjdk:21-bookworm

WORKDIR /dir

# Copy and rename to app.jar
COPY --from=builder /src/target/day16-0.0.1-SNAPSHOT.jar app.jar

EXPOSE ${PORT}

ENTRYPOINT SERVER_PORT=${PORT} java -jar ./app.jar